### PR TITLE
Badge-Link fix

### PR DESCRIPTION
**Pull request by stbischof**
fix link to `groups` [feature](https://github.com/apache/sling-aggregator/blob/master/docs/groups/feature.md) not `group` [feature](https://github.com/apache/sling-aggregator/blob/master/docs/group/feature.md)

### CODE REVIEW

**Comment by rombert** [comment]
Thanks for the PR @stbischof . IIRC we generate these badges with the scripts from https://github.com/apache/sling-aggregator . @klcodanr  - is this something we should fix in the scripts instead?

**Comment by stbischof** [comment]
Ok, good to know that a script does this.

The line with the missing `s`.
https://github.com/apache/sling-aggregator/blob/59881f915e3a1b7f51cb0e1e69eb6b6e438d89c1/generate-badges.groovy#L60

**Comment by rombert** [comment]
@stbischof  - I think you can then send a PR for the aggregator? I am not sure how many projects need a rebuild, but all the _feature_ ones I checked need it.

**Comment by stbischof** [comment]
fix script PR: https://github.com/apache/sling-aggregator/pull/3

**Comment by cziegeler** [comment]
this seems to be fixed in the script, therefore closing

**Pull request closed without merging**
